#!/bin/sh
#
# bootstrap installs things.

unamestr=`uname`

if [[ "$unamestr" == Linux ]]; then
   . script/apt-get
elif [[ "$unamestr" == Darwin ]]; then
   . script/homebrew
fi


# Run the install (I'd like to pull this out of rake, eventually)
rake install