#!/bin/sh
#
# bootstrap installs things.

unamestr=`uname`

 if [ "$unamestr" = Linux ]; then
    . ~/.dotfiles/script/apt-get
 else
    . ~/.dotfiles/script/homebrew
 fi


echo "#### Install $ZSH ####"
# Run the install (I'd like to pull this out of rake, eventually)
rake install -f ../Rakefile --trace