#!/bin/sh
#
# bootstrap installs things.

unamestr=`uname`

 if [ "$unamestr" = Linux ]; then
    . script/apt-get
 else
    . script/homebrew
 fi



# Run the install (I'd like to pull this out of rake, eventually)
rake install #-f $ZSH/Rakefile